title: Your awesome title
author: ArtVKh
email: your-email@domain.com
description: > # I need to write some sentences to fill this place. It`s my first experience in Git. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
